name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install express

      - name: Build Docker image
        run: docker build -t devops-project-app .

      - name: Run Container test
        run: docker run -d -p 3000:3000 devops-project-app
